name: Docker CI

on:
    push:
        branches: ["dev"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build e push image
              run: |
                docker build --pull -t ${{ env.REGISTRY }}/${{ github.repository }}:latest .
                docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest